# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
    ]
