# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Prakash Rai', max_length=20)),
                ('interests', models.CharField(max_length=100)),
                ('profile', models.TextField(max_length=200)),
            ],
        ),
    ]
