# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='profile',
            field=models.TextField(max_length=300),
        ),
    ]
