# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_auto_20170527_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='blog_description',
            field=models.TextField(default='Mathematics and Computer Science Blog', max_length=325),
        ),
    ]
