# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0004_aboutme_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='blog_description',
            field=models.TextField(default='Mathematics and Computer Science Blog', max_length=400),
        ),
    ]
