# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0007_auto_20170527_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='blog_description',
            field=models.TextField(default='Mathematics and Computer Science Blog', max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='profile',
            field=models.TextField(max_length=500),
        ),
    ]
